name = "linux_ext4_standard"
display_name = "Linux UEFI ext4 單系統"
table = "gpt"
boot_mode = "uefi"
min_disk_size = "32GiB"

[[partitions]]
name = "EFI System"
size = "512MiB"
type = "esp"
filesystem = "fat32"
mount = "/boot/efi"

[[partitions]]
name = "Linux Root"
size = "fill-minus:auto:swap"
type = "linux-filesystem"
filesystem = "ext4"
mount = "/"

[[partitions]]
name = "Linux Swap"
size = "auto:swap"
type = "linux-swap"
filesystem = "swap"
